apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentmemory.fullname" . }}-secrets
  labels:
    {{- include "agentmemory.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  {{- if .openaiApiKey }}
  OPENAI_API_KEY: {{ .openaiApiKey | quote }}
  {{- end }}
  {{- if .anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .anthropicApiKey | quote }}
  {{- end }}
  {{- if .geminiApiKey }}
  GEMINI_API_KEY: {{ .geminiApiKey | quote }}
  {{- end }}
  {{- if .openrouterApiKey }}
  OPENROUTER_API_KEY: {{ .openrouterApiKey | quote }}
  {{- end }}
  {{- if .voyageApiKey }}
  VOYAGE_API_KEY: {{ .voyageApiKey | quote }}
  {{- end }}
  {{- if .cohereApiKey }}
  COHERE_API_KEY: {{ .cohereApiKey | quote }}
  {{- end }}
  {{- if .minimaxApiKey }}
  MINIMAX_API_KEY: {{ .minimaxApiKey | quote }}
  {{- end }}
  {{- if .agentmemorySecret }}
  AGENTMEMORY_SECRET: {{ .agentmemorySecret | quote }}
  {{- end }}
  {{- end }}
